/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.main.java.mainGui;

import views.main.java.Custumer.customerGui;
import views.main.java.Loan.loanGui;
import views.main.java.createAcccount.createAccountGui;
import views.main.java.operations.operationsGui;
import views.main.java.viewAccounts.viewAccountsGui;
import views.main.java.viewCustomer.viewCustomersGui;
import views.main.java.viewLoan.viewLoansGui;
import views.main.java.viewTansactions.viewTransactionsGui;

/**
 *
 * @author DW
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        operation = new javax.swing.JButton();
        createCustomer = new javax.swing.JButton();
        viewAccounts = new javax.swing.JButton();
        createAccount = new javax.swing.JButton();
        createLoan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        viewLoans = new javax.swing.JButton();
        viewTransactions = new javax.swing.JButton();
        viewCustomers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank");

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        operation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        operation.setText("Operations");
        operation.setToolTipText("Operations");
        operation.setBorder(new javax.swing.border.MatteBorder(null));
        operation.setBorderPainted(false);
        operation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        operation.setDefaultCapable(false);
        operation.setFocusPainted(false);
        operation.setFocusable(false);
        operation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationActionPerformed(evt);
            }
        });

        createCustomer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createCustomer.setText("Create Customer");
        createCustomer.setToolTipText("Create Customer");
        createCustomer.setBorder(new javax.swing.border.MatteBorder(null));
        createCustomer.setBorderPainted(false);
        createCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createCustomer.setDefaultCapable(false);
        createCustomer.setFocusPainted(false);
        createCustomer.setFocusable(false);
        createCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCustomerActionPerformed(evt);
            }
        });

        viewAccounts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewAccounts.setText("View Accounts");
        viewAccounts.setToolTipText("View Accounts");
        viewAccounts.setBorder(new javax.swing.border.MatteBorder(null));
        viewAccounts.setBorderPainted(false);
        viewAccounts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAccounts.setDefaultCapable(false);
        viewAccounts.setFocusPainted(false);
        viewAccounts.setFocusable(false);
        viewAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAccountsActionPerformed(evt);
            }
        });

        createAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createAccount.setText("Create Account");
        createAccount.setToolTipText("Create Account");
        createAccount.setBorder(new javax.swing.border.MatteBorder(null));
        createAccount.setBorderPainted(false);
        createAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccount.setDefaultCapable(false);
        createAccount.setFocusPainted(false);
        createAccount.setFocusable(false);
        createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });

        createLoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createLoan.setText("Create Loan");
        createLoan.setToolTipText("Create Loan");
        createLoan.setBorder(new javax.swing.border.MatteBorder(null));
        createLoan.setBorderPainted(false);
        createLoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createLoan.setDefaultCapable(false);
        createLoan.setFocusPainted(false);
        createLoan.setFocusable(false);
        createLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLoanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bank");

        viewLoans.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewLoans.setText("View Loans");
        viewLoans.setToolTipText("View Customers");
        viewLoans.setBorder(new javax.swing.border.MatteBorder(null));
        viewLoans.setBorderPainted(false);
        viewLoans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewLoans.setDefaultCapable(false);
        viewLoans.setFocusPainted(false);
        viewLoans.setFocusable(false);
        viewLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLoansActionPerformed(evt);
            }
        });

        viewTransactions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewTransactions.setText("View Transactions");
        viewTransactions.setToolTipText("View Customers");
        viewTransactions.setBorder(new javax.swing.border.MatteBorder(null));
        viewTransactions.setBorderPainted(false);
        viewTransactions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTransactions.setDefaultCapable(false);
        viewTransactions.setFocusPainted(false);
        viewTransactions.setFocusable(false);
        viewTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionsActionPerformed(evt);
            }
        });

        viewCustomers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewCustomers.setText("View Customers");
        viewCustomers.setToolTipText("View Customers");
        viewCustomers.setBorder(new javax.swing.border.MatteBorder(null));
        viewCustomers.setBorderPainted(false);
        viewCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewCustomers.setDefaultCapable(false);
        viewCustomers.setFocusPainted(false);
        viewCustomers.setFocusable(false);
        viewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(createCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(createAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(operation, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operation, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCustomerActionPerformed
        customerGui frame = new customerGui();
        frame.setVisible(true);
    }//GEN-LAST:event_createCustomerActionPerformed

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
        createAccountGui frame = new createAccountGui();
        frame.setVisible(true);    }//GEN-LAST:event_createAccountActionPerformed

    private void createLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLoanActionPerformed

        loanGui frame = new loanGui();
        frame.setVisible(true);


    }//GEN-LAST:event_createLoanActionPerformed

    private void operationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationActionPerformed
        operationsGui frame = new operationsGui();
        frame.setVisible(true);
    }//GEN-LAST:event_operationActionPerformed

    private void viewAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAccountsActionPerformed
        viewAccountsGui frame = new viewAccountsGui();
        frame.setVisible(true);
    }//GEN-LAST:event_viewAccountsActionPerformed

    private void viewLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLoansActionPerformed
        viewLoansGui frame = new viewLoansGui();
        frame.setVisible(true);
    }//GEN-LAST:event_viewLoansActionPerformed

    private void viewTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionsActionPerformed
        viewTransactionsGui frame = new viewTransactionsGui();
        frame.setVisible(true);
    }//GEN-LAST:event_viewTransactionsActionPerformed

    private void viewCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomersActionPerformed
         viewCustomersGui frame = new viewCustomersGui();
        frame.setVisible(true);
    }//GEN-LAST:event_viewCustomersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainFrame frame = new mainFrame();
                frame.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccount;
    private javax.swing.JButton createCustomer;
    private javax.swing.JButton createLoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton operation;
    private javax.swing.JButton viewAccounts;
    private javax.swing.JButton viewCustomers;
    private javax.swing.JButton viewLoans;
    private javax.swing.JButton viewTransactions;
    // End of variables declaration//GEN-END:variables
}
